name: Tests with Coverage
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
jobs:
  lint_test_coverage:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint     
      - name: tsc
        uses: icrawl/action-tsc@v1
        with:
          project: ./tsconfig.json        
      - name: Install Playwright Chromium
        run:  npx playwright install-deps chromium
      - name: Run Playwright tests
        run: npm run test:coverage
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3